name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://richardford.online
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{secrets.SERVER_IP_ADDRESS}} >> ~/.ssh/known_hosts

    - name: Deploy to Digital Ocean
      run: |
        ssh -o StrictHostKeyChecking=no root@${{secrets.SERVER_IP_ADDRESS}} << 'ENDSSH'
        cd /var/www/Blog/blog
        git pull origin main
        composer install
        npm install
        npm run build
        php artisan migrate
        php artisan cache:clear
        php artisan config:clear
        ENDSSH
