name: Build - Test - Deploy

on:
  push:
    branches:
      - main

jobs:
  build_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./blog

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'

    - uses: actions/checkout@v4

    - name: Copy .env
      run:
        php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: |
        composer update
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: |
        php artisan key:generate

    - name: Directory Permissions
      run: |
        chmod -R 777 storage bootstrap/cache

    - name: Install NPM Dependencies
      run: |
        npm install

    - name: Build Vite Assets
      run: |
        npm run build

    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: ${{ github.workspace }}/blog/database/database.sqlite
      run: 
        vendor/bin/phpunit

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build_test
    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: unnecessary

    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SERVER_IP_ADDRESS }}  >> ~/.ssh/known_hosts

    - name: Deploy to Digital Ocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP_ADDRESS }}
        username:  ${{ secrets.SSH_USER }}
        port: ${{ secrets.SERVER_PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/Blog/blog
          git pull origin main
          sudo -u rford composer install
          sudo -u rford npm install
          sudo -u rford npm run build
          sudo -u rford php artisan migrate --force
          sudo -u rford php artisan cache:clear
          sudo -u rford php artisan config:clear
